package com.cloudvault.domain;

import jakarta.persistence.*;
import java.time.Instant;

/**
 * A physically stored blob. {@code storageKey} is generated by Cloud Vault
 * (sharded UUID) and is never derived from user input; {@code physicalReference}
 * is the absolute path resolved at write time.
 */
@Entity
@Table(name = "storage_objects")
public class StorageObject {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(optional = false)
    @JoinColumn(name = "pool_id")
    private StoragePool pool;

    @ManyToOne(fetch = FetchType.EAGER, optional = false)
    @JoinColumn(name = "location_id")
    private StorageLocation location;

    @Column(name = "storage_key", nullable = false, unique = true, length = 255)
    private String storageKey;

    @Column(name = "physical_reference", nullable = false, length = 1024)
    private String physicalReference;

    @Column(name = "size_bytes", nullable = false)
    private long sizeBytes;

    @Column(name = "checksum_sha256", nullable = false, length = 64)
    private String checksumSha256;

    @Column(name = "content_type", length = 128)
    private String contentType;

    @Column(name = "created_at", nullable = false)
    private Instant createdAt = Instant.now();

    @Column(name = "verified_at")
    private Instant verifiedAt;

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public StoragePool getPool() { return pool; }
    public void setPool(StoragePool pool) { this.pool = pool; }
    public StorageLocation getLocation() { return location; }
    public void setLocation(StorageLocation location) { this.location = location; }
    public String getStorageKey() { return storageKey; }
    public void setStorageKey(String storageKey) { this.storageKey = storageKey; }
    public String getPhysicalReference() { return physicalReference; }
    public void setPhysicalReference(String physicalReference) { this.physicalReference = physicalReference; }
    public long getSizeBytes() { return sizeBytes; }
    public void setSizeBytes(long sizeBytes) { this.sizeBytes = sizeBytes; }
    public String getChecksumSha256() { return checksumSha256; }
    public void setChecksumSha256(String checksumSha256) { this.checksumSha256 = checksumSha256; }
    public String getContentType() { return contentType; }
    public void setContentType(String contentType) { this.contentType = contentType; }
    public Instant getCreatedAt() { return createdAt; }
    public Instant getVerifiedAt() { return verifiedAt; }
    public void setVerifiedAt(Instant verifiedAt) { this.verifiedAt = verifiedAt; }
}
