/* Decompiler 11ms, total 269ms, lines 22 */
package src.main.java.com.mountblue.googledrive.controller;

@Controller
public class RecentController {
   @Autowired
   private ParentFolderService parentFolderService;
   @Autowired
   private FileService fileService;
   @Autowired
   private FolderService folderService;
   @Autowired
   private UserService userService;

   public RecentController() {
      throw new Error("Unresolved compilation problems: \n\tThe type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files\n\tThe type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files\n\tThe declared package \"com.mountblue.googledrive.controller\" does not match the expected package \"src.main.java.com.mountblue.googledrive.controller\"\n\tThe import com cannot be resolved\n\tThe import com cannot be resolved\n\tThe import com cannot be resolved\n\tThe import com cannot be resolved\n\tThe import com cannot be resolved\n\tThe import com cannot be resolved\n\tThe import com cannot be resolved\n\tThe import com cannot be resolved\n\tThe import org cannot be resolved\n\tThe import org cannot be resolved\n\tThe import org cannot be resolved\n\tThe import org cannot be resolved\n\tThe import org cannot be resolved\n\tThe import org cannot be resolved\n\tThe import java.security cannot be resolved\n\tThe import java.util cannot be resolved\n\tThe import java.util cannot be resolved\n\tThe import java.util cannot be resolved\n\tController cannot be resolved to a type\n\tImplicit super constructor Object() is undefined for default constructor. Must define an explicit constructor\n\tAutowired cannot be resolved to a type\n\tParentFolderService cannot be resolved to a type\n\tAutowired cannot be resolved to a type\n\tFileService cannot be resolved to a type\n\tAutowired cannot be resolved to a type\n\tFolderService cannot be resolved to a type\n\tAutowired cannot be resolved to a type\n\tUserService cannot be resolved to a type\n\tGetMapping cannot be resolved to a type\n\tString cannot be resolved to a type\n\tModel cannot be resolved to a type\n\tPrincipal cannot be resolved to a type\n\tOAuth2AuthenticationToken cannot be resolved to a type\n\tOAuth2AuthenticationToken cannot be resolved to a type\n\tMap cannot be resolved to a type\n\tString cannot be resolved to a type\n\tObject cannot be resolved to a type\n\tString cannot be resolved to a type\n\tString cannot be resolved to a type\n\tUsers cannot be resolved to a type\n\tUserService cannot be resolved to a type\n\tList cannot be resolved to a type\n\tParentFolder cannot be resolved to a type\n\tParentFolderService cannot be resolved to a type\n\tParentFolder cannot be resolved to a type\n\tParentFolderService cannot be resolved to a type\n\tParentFolder cannot be resolved to a type\n\tParentFolderService cannot be resolved to a type\n\tList cannot be resolved to a type\n\tFile cannot be resolved to a type\n\tFileService cannot be resolved to a type\n\tList cannot be resolved to a type\n\tFolder cannot be resolved to a type\n\tFolderService cannot be resolved to a type\n\tSystem cannot be resolved\n\tFolder cannot be resolved to a type\n\tFile cannot be resolved to a type\n\tIterator cannot be resolved to a type\n\tFile cannot be resolved to a type\n\tFile cannot be resolved to a type\n");
   }

   public String Recent(Model var1, Principal var2) {
      throw new Error("Unresolved compilation problems: \n\tGetMapping cannot be resolved to a type\n\tString cannot be resolved to a type\n\tModel cannot be resolved to a type\n\tPrincipal cannot be resolved to a type\n\tOAuth2AuthenticationToken cannot be resolved to a type\n\tOAuth2AuthenticationToken cannot be resolved to a type\n\tMap cannot be resolved to a type\n\tString cannot be resolved to a type\n\tObject cannot be resolved to a type\n\tString cannot be resolved to a type\n\tString cannot be resolved to a type\n\tUsers cannot be resolved to a type\n\tUserService cannot be resolved to a type\n\tList cannot be resolved to a type\n\tParentFolder cannot be resolved to a type\n\tParentFolderService cannot be resolved to a type\n\tParentFolder cannot be resolved to a type\n\tParentFolderService cannot be resolved to a type\n\tParentFolder cannot be resolved to a type\n\tParentFolderService cannot be resolved to a type\n\tList cannot be resolved to a type\n\tFile cannot be resolved to a type\n\tFileService cannot be resolved to a type\n\tList cannot be resolved to a type\n\tFolder cannot be resolved to a type\n\tFolderService cannot be resolved to a type\n\tSystem cannot be resolved\n\tFolder cannot be resolved to a type\n\tFile cannot be resolved to a type\n\tIterator cannot be resolved to a type\n\tFile cannot be resolved to a type\n\tFile cannot be resolved to a type\n");
   }
}
