package com.cloudvault.service.storage;

import com.cloudvault.domain.StorageLocation;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Path;

/**
 * Abstraction over physical blob storage. Implementations must be safe
 * against path traversal: the storage key is always generated by Cloud Vault
 * and implementations must resolve it strictly beneath the location root.
 */
public interface StorageProvider {

    /** Result of a successful write: verified size and SHA-256 checksum. */
    record WriteResult(long sizeBytes, String checksumSha256, String physicalReference) {}

    /** Streams {@code in} into the location at {@code storageKey}. Streams, never buffers in RAM. */
    WriteResult write(StorageLocation location, String storageKey, InputStream in) throws IOException;

    /** Opens a read stream starting at {@code offset} for up to {@code length} bytes ({@code -1} = to EOF). */
    InputStream openRead(StorageLocation location, String storageKey, long offset, long length) throws IOException;

    void delete(StorageLocation location, String storageKey) throws IOException;

    boolean exists(StorageLocation location, String storageKey);

    long size(StorageLocation location, String storageKey) throws IOException;

    /** Resolves the absolute path for a key, rejecting anything outside the root. */
    Path resolve(StorageLocation location, String storageKey);

    /** Generates a fresh, collision-free storage key (sharded UUID). */
    String newStorageKey();
}
